# Generated by Django 3.2.13 on 2022-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='lobby', max_length=16),
            preserve_default=False,
        ),
    ]
